version: '3.8'

services:
  next-app:
    image: nextjs-docker:local
    container_name: nextjs-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
