name: 🚀 Next.js CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: 🎉 Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Ajusta según tu servidor

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: npm run build

      - name: 🧹 Create Passenger restart file
        run: |
          mkdir -p tmp
          echo $RANDOM > tmp/restart.txt

      - name: 📂 Sync files to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /home/andesaca/serviciosquimicosec.com/ # Asegúrate que coincide con PassengerAppRoot
          exclude: |
            **/.next/cache/**
            **/.git/**
            **/.github/**
            node_modules/**
            README.md
            .gitignore
            tailwind.config.js
            postcss.config.js
            .eslintrc.json
